// End-to-end smoke test: builds a throwaway MV-shaped project in a temp dir,
// starts the compiled server over stdio, and exercises one tool from each group.
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";

const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "mv-mcp-smoke-"));
const dataDir = path.join(tmp, "data");
await fs.mkdir(dataDir, { recursive: true });
await fs.mkdir(path.join(tmp, "js", "plugins"), { recursive: true });
await fs.writeFile(path.join(tmp, "Game.rpgproject"), "RPGMV 1.6.2");

const actor = (id, name) => ({
  id, name, nickname: "", classId: 1, initialLevel: 1, maxLevel: 99,
  characterName: "Actor1", characterIndex: 0, faceName: "Actor1", faceIndex: 0,
  battlerName: "", equips: [0, 0, 0, 0, 0], traits: [], note: "", profile: "",
});
await fs.writeFile(path.join(dataDir, "Actors.json"),
  JSON.stringify([null, actor(1, "Harold"), actor(2, "Therese")]));
for (const f of ["Classes", "Skills", "Items", "Weapons", "Armors", "Enemies",
  "Troops", "States", "Animations", "Tilesets", "CommonEvents"]) {
  await fs.writeFile(path.join(dataDir, `${f}.json`), "[null]");
}
await fs.writeFile(path.join(dataDir, "System.json"), JSON.stringify({
  gameTitle: "Smoke Test Quest", currencyUnit: "G", startMapId: 1, startX: 5, startY: 5,
  switches: ["", "Opened Chest"], variables: ["", "Quest Progress"],
}));
await fs.writeFile(path.join(dataDir, "MapInfos.json"), JSON.stringify(
  [null, { id: 1, name: "Town", parentId: 0, order: 1, expanded: false, scrollX: 0, scrollY: 0 }]));
await fs.writeFile(path.join(dataDir, "Map001.json"), JSON.stringify({
  width: 10, height: 10, tilesetId: 1, displayName: "Town",
  bgm: { name: "", pan: 0, pitch: 100, volume: 90 },
  data: new Array(10 * 10 * 6).fill(0),
  events: [null],
  note: "",
}));
await fs.writeFile(path.join(tmp, "js", "plugins", "Community_Basic.js"),
  "/*: @plugindesc Basic plugin */\n");
await fs.writeFile(path.join(tmp, "js", "plugins.js"),
  '// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n' +
  '{"name":"Community_Basic","status":true,"description":"Basic plugin","parameters":{"cacheLimit":"20"}}\n];\n');

const client = new Client({ name: "smoke", version: "0.0.0" });
await client.connect(new StdioClientTransport({
  command: process.execPath,
  args: [path.join(import.meta.dirname, "..", "dist", "index.js")],
}));

let failures = 0;
async function call(name, args, check) {
  const res = await client.callTool({ name, arguments: args });
  const text = res.content?.[0]?.text ?? "";
  const ok = !res.isError && (!check || check(text));
  console.log(`${ok ? "PASS" : "FAIL"} ${name}`);
  if (!ok) {
    failures++;
    console.log(`     ${text.slice(0, 300)}`);
  }
  return text;
}

const tools = await client.listTools();
console.log(`server exposes ${tools.tools.length} tools`);

await call("set_project", { path: tmp }, (t) => t.includes("Project set"));
await call("get_project_info", {}, (t) => t.includes("Smoke Test Quest"));
await call("list_records", { type: "actors" }, (t) => t.includes("Harold"));
await call("get_record", { type: "actors", id: 2 }, (t) => t.includes("Therese"));
await call("update_record", { type: "actors", id: 1, data: { nickname: "Hero" } },
  (t) => t.includes("Hero"));
await call("create_record", { type: "items",
  data: { name: "Potion", iconIndex: 176, price: 50, note: "", description: "Restores HP." } },
  (t) => t.includes('"id": 1'));
await call("get_system", { key: "switches" }, (t) => t.includes("Opened Chest"));
await call("update_system", { data: { startX: 7 } }, (t) => t.includes("startX"));
await call("list_maps", {}, (t) => t.includes("Town"));
await call("get_map", { mapId: 1 }, (t) => t.includes("omitted"));
await call("create_event", { mapId: 1, name: "Chest", x: 3, y: 4 },
  (t) => t.includes('"eventId": 1'));
await call("get_event", { mapId: 1, eventId: 1 }, (t) => t.includes("Chest"));
await call("update_event", { mapId: 1, eventId: 1,
  event: { name: "Chest", x: 3, y: 4, note: "", pages: [] } }, (t) => t.includes("updated"));
await call("delete_event", { mapId: 1, eventId: 1 }, (t) => t.includes("deleted"));
await call("event_command_reference", {}, (t) => t.includes("101 Show Text"));
await call("list_plugins", {}, (t) => t.includes("Community_Basic"));
await call("configure_plugin", { name: "Community_Basic", parameters: { cacheLimit: "30" } },
  (t) => t.includes('"cacheLimit":"30"') || t.includes('"cacheLimit": "30"'));
await call("create_plugin", { name: "SmokePlugin", description: "test plugin" },
  (t) => t.includes("SmokePlugin"));
await call("read_plugin", { name: "SmokePlugin" }, (t) => t.includes("@plugindesc"));
await call("write_plugin", { name: "SmokePlugin", code: "// overwritten\n" },
  (t) => t.includes("written"));
// skill helpers
await call("create_damage_skill", { name: "Fireball", formula: "a.mat * 4 - b.mdf * 2",
  elementId: 2, mpCost: 12, description: "Hurls a ball of fire." },
  (t) => t.includes('"formula": "a.mat * 4 - b.mdf * 2"') && t.includes('"type": 1'));
await call("create_healing_skill", { name: "Cure", formula: "a.mat * 2 + 200",
  removeStates: [4] }, (t) => t.includes('"type": 3') && t.includes('"code": 22'));
await call("create_buff_skill", { name: "Barrier", buffs: [{ param: 3, turns: 5 }] },
  (t) => t.includes('"code": 31') && t.includes('"scope": 7'));
await call("create_state_skill", { name: "Poison Cloud",
  states: [{ stateId: 4, chance: 80 }], scope: 2 },
  (t) => t.includes('"code": 21') && t.includes('"value1": 0.8'));

// search
await call("search_records", { query: "fire" }, (t) => t.includes("Fireball"));
await call("search_records", { query: "harold", type: "actors" }, (t) => t.includes('"id": 1'));

// add_event_command + command search
await call("create_event", { mapId: 1, name: "Guard", x: 2, y: 2 }, (t) => t.includes("Guard"));
await call("add_event_command", { mapId: 1, eventId: 2, commands: [
  { code: 101, parameters: ["", 0, 0, 2] },
  { code: 401, parameters: ["Halt! Who goes there?"] },
] }, (t) => t.includes('"inserted": 2'));
await call("search_map_events", { query: "guard" }, (t) => t.includes('"eventId": 2'));
await call("search_map_events", { query: "halt! who", searchCommands: true },
  (t) => t.includes("command 401"));

// system name setters
await call("set_switch_name", { id: 5, name: "Boss Defeated" }, (t) => t.includes("Boss Defeated"));
await call("set_variable_name", { id: 2, name: "Gold Earned" }, (t) => t.includes("Gold Earned"));
await call("get_system", { key: "switches" }, (t) => t.includes("Boss Defeated"));

// dialogue helper (5 lines -> 2 message boxes: 2x code 101 + 5x code 401 = 7 commands)
await call("add_dialogue", { mapId: 1, eventId: 2,
  lines: ["Line one.", "Line two.", "Line three.", "Line four.", "Line five."],
  faceName: "Actor1" },
  (t) => t.includes('"inserted": 7') && t.includes('"messageBoxes": 2'));

// map creation
await call("create_map", { name: "Cave", width: 20, height: 15 },
  (t) => t.includes('"mapId": 2'));
await call("list_maps", {}, (t) => t.includes("Cave"));
await call("create_event", { mapId: 2, name: "Miner", x: 1, y: 1 }, (t) => t.includes("Miner"));

// validation: healthy except known quirks we introduce
await call("add_event_command", { mapId: 2, eventId: 1, commands: [
  { code: 201, parameters: [0, 99, 5, 5, 2, 0] },
] }, (t) => t.includes('"inserted": 1'));
const validation = await call("validate_project", {},
  (t) => t.includes('"ok": true') && t.includes("transfers the player to map 99"));
if (!validation.includes('"errors": []')) { console.log("FAIL validation should have no errors"); failures++; }

// backups: mangle a record, then restore it
await call("list_backups", {}, (t) => t.includes("data/Actors.json"));
await call("update_record", { type: "actors", id: 1, data: { name: "RUINED" } },
  (t) => t.includes("RUINED"));
await call("restore_backup", { file: "data/Actors.json" }, (t) => t.includes("data/Actors.json"));
await call("get_record", { type: "actors", id: 1 }, (t) => t.includes("Harold") && !t.includes("RUINED"));

await call("playtest_start", { mode: "browser", port: 8391 }, (t) => t.includes("http://127.0.0.1:8391"));
const res = await fetch("http://127.0.0.1:8391/data/System.json");
console.log(`${res.ok ? "PASS" : "FAIL"} http fetch of data/System.json (${res.status})`);
if (!res.ok) failures++;
await call("playtest_status", {}, (t) => t.includes('"running": true'));
await call("playtest_stop", {}, (t) => t.includes("http server"));

// error paths
const bad = await client.callTool({ name: "get_record", arguments: { type: "actors", id: 99 } });
console.log(`${bad.isError ? "PASS" : "FAIL"} get_record on missing id returns error`);
if (!bad.isError) failures++;

await client.close();
await fs.rm(tmp, { recursive: true, force: true });
console.log(failures === 0 ? "\nAll smoke tests passed." : `\n${failures} FAILURES`);
process.exit(failures === 0 ? 0 : 1);
