import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import fs from "node:fs/promises";
import path from "node:path";
import { Project, ProjectError } from "../project.js";
import { safe, textResult } from "../util.js";

interface PluginEntry {
  name: string;
  status: boolean;
  description: string;
  parameters: Record<string, string>;
}

function pluginsJsPath(project: Project): string {
  return path.join(project.root, "js", "plugins.js");
}

function pluginFilePath(project: Project, name: string): string {
  if (!/^[\w. -]+$/.test(name)) {
    throw new ProjectError(`Invalid plugin name: ${name}`);
  }
  return path.join(project.root, "js", "plugins", `${name}.js`);
}

export async function readPluginList(project: Project): Promise<PluginEntry[]> {
  let raw: string;
  try {
    raw = await fs.readFile(pluginsJsPath(project), "utf8");
  } catch {
    return [];
  }
  const match = raw.match(/\[[\s\S]*\]/);
  if (!match) {
    throw new ProjectError("js/plugins.js exists but no plugin array was found in it.");
  }
  try {
    return JSON.parse(match[0]) as PluginEntry[];
  } catch (err) {
    throw new ProjectError(`Could not parse plugin list: ${(err as Error).message}`);
  }
}

async function writePluginList(project: Project, plugins: PluginEntry[]): Promise<void> {
  await project.backup(pluginsJsPath(project));
  const lines = plugins.map((p) => JSON.stringify(p));
  const text =
    "// Generated by RPG Maker.\n" +
    "// Do not edit this file directly.\n" +
    "var $plugins =\n[\n" +
    lines.join(",\n") +
    "\n];\n";
  await fs.writeFile(pluginsJsPath(project), text, "utf8");
}

function pluginScaffold(name: string, description: string): string {
  return `//=============================================================================
// ${name}.js
//=============================================================================

/*:
 * @plugindesc ${description}
 * @author
 *
 * @help ${name}.js
 *
 * This plugin does not provide plugin commands.
 */

(function() {
    'use strict';

    // Plugin code goes here.

})();
`;
}

export function registerPluginTools(server: McpServer, project: Project): void {
  server.registerTool(
    "list_plugins",
    {
      title: "List plugins",
      description: "List all plugins registered in js/plugins.js with status and parameters.",
      inputSchema: {},
    },
    safe(async () => textResult(await readPluginList(project)))
  );

  server.registerTool(
    "configure_plugin",
    {
      title: "Configure plugin",
      description:
        "Enable/disable a registered plugin and/or merge new values into its parameters (parameter values are always strings in RPG Maker MV).",
      inputSchema: {
        name: z.string().describe("Plugin name as it appears in list_plugins"),
        status: z.boolean().optional().describe("true = enabled, false = disabled"),
        parameters: z
          .record(z.string())
          .optional()
          .describe("Parameter values to merge into the plugin's parameters"),
      },
    },
    safe(async ({ name, status, parameters }) => {
      const plugins = await readPluginList(project);
      const plugin = plugins.find((p) => p.name === name);
      if (!plugin) {
        throw new ProjectError(
          `No plugin named '${name}' is registered. Registered: ${plugins.map((p) => p.name).join(", ") || "(none)"}`
        );
      }
      if (status !== undefined) plugin.status = status;
      if (parameters) Object.assign(plugin.parameters, parameters);
      await writePluginList(project, plugins);
      return textResult({ configured: plugin });
    })
  );

  server.registerTool(
    "add_plugin",
    {
      title: "Register plugin",
      description:
        "Register an existing js/plugins/<name>.js file in the plugin list. Fails if the file does not exist (use create_plugin to make a new one).",
      inputSchema: {
        name: z.string(),
        status: z.boolean().default(true),
        description: z.string().default(""),
        parameters: z.record(z.string()).default({}),
      },
    },
    safe(async ({ name, status, description, parameters }) => {
      try {
        await fs.access(pluginFilePath(project, name));
      } catch {
        throw new ProjectError(
          `js/plugins/${name}.js does not exist. Use create_plugin to create it.`
        );
      }
      const plugins = await readPluginList(project);
      if (plugins.some((p) => p.name === name)) {
        throw new ProjectError(`Plugin '${name}' is already registered. Use configure_plugin.`);
      }
      plugins.push({ name, status, description, parameters });
      await writePluginList(project, plugins);
      return textResult({ registered: name, totalPlugins: plugins.length });
    })
  );

  server.registerTool(
    "remove_plugin",
    {
      title: "Unregister plugin",
      description:
        "Remove a plugin from js/plugins.js. The plugin's .js file is NOT deleted.",
      inputSchema: { name: z.string() },
    },
    safe(async ({ name }) => {
      const plugins = await readPluginList(project);
      const index = plugins.findIndex((p) => p.name === name);
      if (index === -1) {
        throw new ProjectError(`No plugin named '${name}' is registered.`);
      }
      plugins.splice(index, 1);
      await writePluginList(project, plugins);
      return textResult({ unregistered: name, totalPlugins: plugins.length });
    })
  );

  server.registerTool(
    "create_plugin",
    {
      title: "Create plugin",
      description:
        "Create a new plugin file in js/plugins/ and register it. If no code is given, a standard MV plugin scaffold (with @plugindesc header) is written. Fails if the file already exists.",
      inputSchema: {
        name: z.string().describe("Plugin file name without .js"),
        description: z.string().default(""),
        code: z.string().optional().describe("Full JavaScript source; omit for a scaffold"),
        status: z.boolean().default(true),
      },
    },
    safe(async ({ name, description, code, status }) => {
      const filePath = pluginFilePath(project, name);
      try {
        await fs.access(filePath);
        throw new ProjectError(`js/plugins/${name}.js already exists. Use write_plugin to modify it.`);
      } catch (err) {
        if (err instanceof ProjectError) throw err;
      }
      await fs.mkdir(path.dirname(filePath), { recursive: true });
      await fs.writeFile(filePath, code ?? pluginScaffold(name, description), "utf8");
      const plugins = await readPluginList(project);
      if (!plugins.some((p) => p.name === name)) {
        plugins.push({ name, status, description, parameters: {} });
        await writePluginList(project, plugins);
      }
      return textResult({ created: `js/plugins/${name}.js`, registered: true });
    })
  );

  server.registerTool(
    "read_plugin",
    {
      title: "Read plugin source",
      description: "Read the JavaScript source of js/plugins/<name>.js.",
      inputSchema: { name: z.string() },
    },
    safe(async ({ name }) => {
      const filePath = pluginFilePath(project, name);
      try {
        return textResult(await fs.readFile(filePath, "utf8"));
      } catch {
        throw new ProjectError(`js/plugins/${name}.js does not exist.`);
      }
    })
  );

  server.registerTool(
    "write_plugin",
    {
      title: "Write plugin source",
      description: "Overwrite the JavaScript source of an existing js/plugins/<name>.js.",
      inputSchema: {
        name: z.string(),
        code: z.string().describe("Complete new file contents"),
      },
    },
    safe(async ({ name, code }) => {
      const filePath = pluginFilePath(project, name);
      try {
        await fs.access(filePath);
      } catch {
        throw new ProjectError(`js/plugins/${name}.js does not exist. Use create_plugin first.`);
      }
      await project.backup(filePath);
      await fs.writeFile(filePath, code, "utf8");
      return textResult({ written: `js/plugins/${name}.js`, bytes: code.length });
    })
  );
}
